### PR TITLE
fix(service): prepend cb-mpc curve prefix to marshalPubShare output

### LINKED ISSUE #11: PartialDecryptTDH2 returns pub_share without cb-mpc curve prefix, causing TDH2Combine to fail
### Background

`PartialDecryptTDH2` performs TDH2 threshold partial decryption and returns each node's public share point (`pub_share`) to the caller. The caller then passes these shares to `mpc.TDH2Combine` to reconstruct the plaintext.

### Description

`marshalPubShare` in `service/dkg_partial_decrypt.go` serializes the Edwards25519 public share point using `kyber.Point.MarshalBinary()`, which returns a raw 32-byte point with **no curve-type prefix**.

However, cb-mpc's `TDH2Combine` requires all ECC points — including each participant's `Qi` (public share point) — to be in cb-mpc's internal serialization format:

`[ 0x04 (SEC1 uncompressed prefix) | 0x3f (cb-mpc Ed25519 curve ID) | 32-byte point ]`

Without these 2 prefix bytes, cb-mpc cannot identify the curve type and fails during deserialization of `Qi`, producing:

```
Error 0xff040001: Curve not found
Error 0xff040001: deser Qi failed
tdh2_combine_ac failed: -16515071
```

### Affected Code

`service/dkg_partial_decrypt.go` — `marshalPubShare`

`buildTDH2PublicKey` in the same file already handles the global public key correctly:

```go
// buildTDH2PublicKey — correct, prefix included
tdhPointBytes := append([]byte{sec1UncompressedPrefix, tdh2Edwards25519CurveID}, dkgPubKey...)
```
marshalPubShare was missing the same treatment:

```
// marshalPubShare — incorrect, prefix missing
return pubSharePoint.MarshalBinary()
```

### Fix
Prepend `[]byte{sec1UncompressedPrefix, tdh2Edwards25519CurveID}` to the output of `pubSharePoint.MarshalBinary()`, consistent with `buildTDH2PublicKey`:

```
pointBz, err := pubSharePoint.MarshalBinary()
if err != nil {
    return nil, err
}
return append([]byte{sec1UncompressedPrefix, tdh2Edwards25519CurveID}, pointBz...), nil
```

### Impact
Any caller that passes pub_share values from `PartialDecryptTDH2` into `mpc.TDH2Combine` will receive a deserialization error. The entire TDH2 threshold decryption feature is non-functional until this is resolved.

### PR DESCRIPTION
**Pull request by 0xHansLee**
##  Summary

- `marshalPubShare` returned raw `Edwards25519` point bytes without the [0x04, 0x3f] cb-mpc curve prefix, causing `TDH2Combine` to fail with "Curve not found" deserialization error
- Aligned with `buildTDH2PublicKey` which already prepends the prefix in the same file
- Added unit tests for `marshalPubShare`

Closes #11

### CODE REVIEW

File: service/dkg_partial_decrypt.go [hunk 1]
```diff
@@ -242,7 +242,13 @@ func marshalPubShare(scalar kyber.Scalar) ([]byte, error) {
 	suite := edwards25519.NewBlakeSHA256Ed25519()
 	pubSharePoint := suite.Point().Mul(scalar, nil)
 
-	return pubSharePoint.MarshalBinary()
+	pointBz, err := pubSharePoint.MarshalBinary()
+	if err != nil {
+		return nil, err
+	}
+
+	// Prepend cb-mpc curve prefix so TDH2Combine can deserialize the point.
```
Comment (wo-o) [inline service/dkg_partial_decrypt.go]: Good alignment with existing constants. Consider verifying these constants match cb-mpc library expectations and adding a comment referencing where they're defined for maintainability.

**Review by wo-o — COMMENTED** [review]
Good fix for cb-mpc curve prefix issue. The solution correctly aligns `marshalPubShare` with `buildTDH2PublicKey` format requirements. Test coverage is comprehensive, verifying prefix correctness, deterministic behavior, and format compatibility.

File: service/dkg_partial_decrypt_test.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+
+func TestMarshalPubShare(t *testing.T) {
+	suite := edwards25519.NewBlakeSHA256Ed25519()
+
+	t.Run("output has cb-mpc curve prefix", func(t *testing.T) {
+		scalar := suite.Scalar().Pick(suite.RandomStream())
+		result, err := marshalPubShare(scalar)
+		require.NoError(t, err)
+
+		require.Greater(t, len(result), 2, "result must be at least prefix + point bytes")
```
Comment (wo-o) [inline service/dkg_partial_decrypt_test.go]: Consider using `require.GreaterOrEqual(t, len(result), 2, ...)` for clarity, though the current check is functionally correct.

File: service/dkg_partial_decrypt_test.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+		scalar := suite.Scalar().Pick(suite.RandomStream())
+		r1, err1 := marshalPubShare(scalar)
+		r2, err2 := marshalPubShare(scalar)
+		require.NoError(t, err1)
+		require.NoError(t, err2)
+		assert.Equal(t, r1, r2, "same scalar must produce identical output")
+	})
+
+	t.Run("different scalars produce different outputs", func(t *testing.T) {
+		s1 := suite.Scalar().Pick(suite.RandomStream())
```
Comment (wo-o) [inline service/dkg_partial_decrypt_test.go]: This test could theoretically fail with extremely low probability if the random scalars are identical. Consider using fixed test vectors for deterministic behavior.
